extends:
  - "eslint:recommended"
  # - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
env:
  node: true
  jest: true

plugins:
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"

parserOptions:
  sourceType: "module"
  project: "./tsconfig.json"

rules:
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": "error"

  prettier/prettier:
    - error
    - singleQuote: true
      semi: true
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
