extends:
  - "eslint:recommended"
  # - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"

plugins:
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"

parserOptions:
  sourceType: "module"
  project: "./tsconfig.json"

rules:
  prettier/prettier:
    - error
    - singleQuote: true
      semi: true
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx