AWSTemplateFormatVersion: 2010-09-09
Description: ---
Metadata: 

Parameters: 
  BucketName:
    Type: String
    Default: coupon-image-bucket
  ACMArn:
    Type: String
  

Mappings: 

Conditions: 

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Ref BucketName
      CorsConfiguration: 
      LifecycleConfiguration: 
      NotificationConfiguration: 
      VersioningConfiguration: 
      WebsiteConfiguration: 
      Tags:
        - Key: key
          Value: value

  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CacheBehaviors:
          - 
            behavior
        DefaultCacheBehavior: 
        IPV6Enabled: true | false
        Origins:
          - 
            origin
      Tags:
        - Key: key
          Value: value

  route53HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: 
      HostedZoneConfig:
        Comment: My hosted zone for example.com
      VPCs:
        - 
          VPCId: "vpc-id"
          VPCRegion: "vpc-region"
      HostedZoneTags:
        - 
          Key: "SampleKey1"
          Value: "SampleValue1"

Outputs:
