swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
  contact:
    name: Yasumasa Takai
    email: m.e.t.e.o.r.07@gmail
    url: https://github.com/kiyoneet
tags:
  - name: Metadata
    description: Metadata related requests
paths: {}